[env:bluepill_f103c8]
platform        = ststm32
board           = bluepill_f103c8
framework       = stm32cube
build_flags     =
    -DSTM32F103xB
    -DUSE_HAL_DRIVER
    -mthumb
    -mcpu=cortex-m3
    -Os
    -ffunction-sections
    -fdata-sections
    -Wall
    -std=c11
    -Wl,--gc-sections
    -Iinclude
build_unflags   =
    -std=gnu11
upload_protocol = stlink
debug_tool      = stlink